### ISSUE TITLE
Problems with Histograms and Plotting Macro 

### ISSUE THREAD

**Issue by amccarrick** [GRIFFINCollaboration/detectorSimulations_v10#76]
Hi, 

I've generated multiple histograms using GRIFFIN, but when I try to combine them (overlay 2, divide 2 etc) in a pretty standard plotting macro (attached), I consistently get errors regarding invalid memory addresses: 

`Processing rootPlotting.C...
#0  0x00007f0a9da071c6 in __GI___wait4 (pid=2822016, stat_loc=stat_loc
entry=0x7ffcb02439a8, options=options
entry=0, usage=usage
entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x00007f0a9da07187 in __GI___waitpid (pid=<optimized out>, stat_loc=stat_loc
entry=0x7ffcb02439a8, options=options
entry=0) at waitpid.c:38
#2  0x00007f0a9d984aa7 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:172
#3  0x00007f0a9dffefcc in TUnixSystem::StackTrace() () from /usr/local/root6.26_debian11/lib/libCore.so
#4  0x00007f0a99867c78 in cling::MultiplexInterpreterCallbacks::PrintStackTrace() () from /usr/local/root6.26_debian11/lib/libCling.so
#5  0x00007f0a9985c81e in cling_runtime_internal_throwIfInvalidPointer () from /usr/local/root6.26_debian11/lib/libCling.so
#6  0x00007f0a97c6f6a7 in ?? ()
#7  0x407dc000346dc5d6 in ?? ()
#8  0x00005608971d0930 in ?? ()
#9  0x00007f0a9985c790 in ?? () from /usr/local/root6.26_debian11/lib/libCling.so
#10 0x0000000000000000 in ?? ()
Error in <HandleInterpreterException>: Trying to access a pointer that points to an invalid memory address..
Execution of your code was aborted.
In file included from input_line_9:1:
/home/msc4/FIPPS/sims/157Gd_ng_FIPPS/rootPlotting.C:274:1: warning: invalid memory pointer passed to a callee:
plot_data[read_counter]->SetLineColor(mycol->GetColor(palette[0][read_counter],palette[1][read_counter],palette[2][read_counter]));`

Unsure if there is a simpler way to combine and compare histograms produced with GRIFFIN, or if I am doing something glaringly obviously wrong. 

rootPlotting.cc: 
[rootPlotting.txt](https://github.com/GRIFFINCollaboration/detectorSimulations_v10/files/9567670/rootPlotting.txt)

**Comment by amccarrick** [comment]
Simple fix - Replace TH1D with TH1F!

**Comment by amccarrick** [comment]
Simple fix - Replace TH1D with TH1F!
